services:
  gitea-db:
    image: postgres
    restart: unless-stopped
    networks:
      - traefik-net
    volumes:
      - gitea-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=gitea
      - POSTGRES_PASSWORD=gitea_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d $${POSTGRES_DB}"]
      start_period: 5s
      interval: 30s
      timeout: 10s
      retries: 10

  gitea:
    image: gitea/gitea:latest
    restart: unless-stopped
    networks:
      - traefik-net
    ports:
      - "2222:22"
    volumes:
      - gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - USER_UID=1000
      - USER_GID=1000
      
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=gitea-db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=postgres
      - GITEA__database__PASSWD=gitea_password
      
      - GITEA__server__SSH_PORT=22
      - GITEA__server__ROOT_URL=http://gitea.localhost
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitea.rule=Host(`gitea.localhost`)
      - traefik.http.routers.gitea.entrypoints=web #,websecure
      - traefik.http.services.gitea.loadbalancer.server.port=3000
      # - traefik.http.routers.gitea.tls.certresolver=letsencrypt-resolver
    depends_on:
      - gitea-db
    
volumes:
  gitea-data:
    driver: local
  gitea-db-data:
    driver: local

networks:
  traefik-net:
    external: true