services:

  excalidraw:
    image: excalidraw/excalidraw:latest
    restart: unless-stopped
    networks:
      - traefik-net
    volumes:
      - excalidraw-data:/app/data
    environment:
      - EXCALIDRAW_BIND_ADDRESS=https://excalidraw.localhost
    labels:
      - traefik.enable=true
      - traefik.http.routers.excalidraw.rule=Host(`excalidraw.localhost`)
      - traefik.http.routers.excalidraw.entrypoints=web # ,websecure
      # - traefik.http.services.excalidraw.loadbalancer.server.port=80
      # - traefik.http.routers.excalidraw.tls.certresolver=letsencrypt-resolver

volumes:
  excalidraw-data:
    driver: local

networks:
  traefik-net:
    external: true