services:

  inngest-postgres:
    image: postgres:18
    networks:
      - traefik-net
    volumes:
      - inngest-postgres-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=inngest
      - POSTGRES_USER=inngest
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U inngest -d inngest"]
      interval: 5s
      timeout: 5s
      retries: 5

  inngest-redis:
    image: redis:7-alpine
    networks:
      - traefik-net
    volumes:
      - inngest-redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  inngest:
    image: inngest/inngest
    command: "inngest start"
    networks:
      - traefik-net
    ports:
      - "8288:8288"
      - "8289:8289"
    environment:
      - INNGEST_EVENT_KEY=5bb638ecdda48016534f4841ac34480e1f4c66e7ea0e4663856fa9f59cada9ad # openssl rand -hex 32
      - INNGEST_SIGNING_KEY=23212f019c3b51887cbefbfc3455c3b593c7862bf92b238d08d0898c421f6896
      - INNGEST_POSTGRES_URI=postgres://inngest:password@inngest-postgres:5432/inngest
      - INNGEST_REDIS_URI=redis://inngest-redis:6379
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8288/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - traefik.enable=true
      - traefik.http.routers.inngest.rule=Host(`inngest.localhost`)
      - traefik.http.routers.inngest.entrypoints=web # ,websecure
      - traefik.http.services.inngest.loadbalancer.server.port=8288
      # - traefik.http.routers.inngest.tls.certresolver=letsencrypt-resolver
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  inngest-postgres-data:
  inngest-redis-data:

networks:
  traefik-net:
    external: true
